LoginMVC/Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LoginMVC.Models
{
    public class Person
    {
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
    }
}

LoginMVC/Controllers/PersonDetailsController.cs
using LoginMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoginMVC.Controllers
{
    public class PersonDetailsController : Controller
    {
        // GET: PersonDetails
        public ActionResult PersonData()
        {
            return View();
        }
        [HttpPost]
        public ActionResult View(Person person)
        {
            return View("About",person);
        }
    }
}

LoginMVC/Views/PersonDetails/About.cshtml
@model LoginMVC.Models.Person
@{
    ViewBag.Title = "about";
}

<h2>about</h2>

Name  :@Model.Name
<br />
phone Number:@Model.PhoneNumber

LoginMVC/Views/PersonDetails/PersonData.cshtml
@model LoginMVC.Models.Person
@{
    ViewBag.Title = "PersonData";
}

<h2>PersonData</h2>

@using (Html.BeginForm("View", "Person"))
{
    <label>Name</label>
    @Html.TextBoxFor(m => m.Name);
    <br />
    <label>Phone Number</label>
    @Html.TextBoxFor(m => m.PhoneNumber);

    <input type="submit" value="Save" />


}

LoginMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "PersonData", "PersonDetails", new { area = "" }, new { @class = "navbar-brand" })
               @* @Html.ActionLink("Application name", "Person", "View", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>